language: php
sudo: false

php:
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml.dist --coverage-clover coverage.xml
  - php -d memory_limit=256M ./vendor/bin/phpstan analyse dvelum/src tests/unit

after_script:
  - php vendor/bin/codacycoverage clover coverage.xml